spring:
  redis:
    database: 15
    host: 127.0.0.1
    port: 6379
    password: root

  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    com.nbb.template.mapper: debug
